import type {AppLocale} from './locale.ts';

type TimeAgoUnit = 'minute' | 'hour' | 'day';

/** 초대받은 양육자가 앱을 직접 검색하지 않도록 공유 문구에 넣는 마켓 주소다. */
const androidStoreUrl =
  'https://play.google.com/store/apps/details?id=com.seorilabs.babycare';
const appleStoreUrl = 'https://apps.apple.com/app/id6792193162';

function englishPlural(value: number, singular: string): string {
  return value === 1 ? singular : `${singular}s`;
}

/**
 * Korean copy is the source shape. `Strings` is derived from it, so `en` fails
 * to typecheck the moment a key is added here and left untranslated.
 */
const ko = {
  /** BCP 47 tag handed to Intl formatters. */
  intlLocale: 'ko-KR',
  /** Endonym shown in the language setting row. */
  languageName: '한국어',

  common: {
    retry: '다시 시도',
    refresh: '새로고침',
    cancel: '취소',
    delete: '삭제',
    close: '닫기',
    next: '다음',
    back: '이전',
    share: '공유',
    now: '지금',
    reset: '초기화',
    otherCaregiver: '다른 양육자',
  },

  tabs: {
    home: '홈',
    timeline: '타임라인',
    stats: '통계',
    more: '더보기',
  },

  duration: {
    hoursMinutes: (hours: number, minutes: number) =>
      `${hours}시간 ${minutes}분`,
    minutes: (minutes: number) => `${minutes}분`,
    seconds: (seconds: number) => `${seconds}초`,
  },

  timeAgo: {
    justNow: '방금',
    soon: '곧',
    past: (value: number, unit: TimeAgoUnit) =>
      `${value}${unit === 'minute' ? '분' : unit === 'hour' ? '시간' : '일'} 전`,
    future: (value: number, unit: TimeAgoUnit) =>
      `${value}${unit === 'minute' ? '분' : unit === 'hour' ? '시간' : '일'} 후`,
  },

  event: {
    breastMilk: (sides: string) => `모유 · ${sides}`,
    leftSide: (duration: string) => `왼쪽 ${duration}`,
    rightSide: (duration: string) => `오른쪽 ${duration}`,
    formula: '분유',
    pumped: '유축 모유',
    solid: '이유식',
    volume: (label: string, milliliters: number) => `${label} ${milliliters}ml`,
    diaperWet: '소변',
    diaperDirty: '대변',
    diaperMixed: '소변 + 대변',
    diaper: (label: string) => `기저귀 · ${label}`,
    nap: '낮잠',
    nightSleep: '밤잠',
    sleepEnded: (label: string, duration: string) => `${label} · ${duration}`,
    sleepActive: (label: string) => `${label} 자는 중`,
    temperature: (temperature: number, site: string) =>
      `체온 · ${temperature.toFixed(1)}°C · ${site}`,
    temperatureArmpit: '겨드랑이',
    temperatureEar: '귀',
    temperatureForehead: '이마',
    temperatureOral: '입',
    temperatureRectal: '직장',
    temperatureOther: '기타',
    medication: (name: string, dose: string) => `복약 · ${name} ${dose}`,
  },

  app: {
    loadingTitle: '공동 기록을 준비하고 있어요',
    loadingText: '계정과 돌봄 그룹을 확인합니다',
    errorTitle: '공동 기록에 연결할 수 없어요',
    splashTitle: '함께 돌보는 오늘',
    splashText: '양육 기록을 준비하고 있어요',
    runtimeLoadErrorTitle: '공동 기록 화면을 열 수 없어요',
    runtimeLoadErrorMessage:
      '공동 기록 화면을 준비하지 못했어요. 다시 시도해 주세요.',
    runtimeLoadRetryLabel: '공동 기록 화면 다시 열기',
    eventSaved: '돌봄 기록을 저장했어요',
    eventUpdated: '돌봄 기록을 수정했어요',
    eventDeleted: '기록을 삭제했어요',
    sleepRecorded: '수면 시간을 기록했어요',
    membershipRemovedNotice: '돌봄 그룹 접근 권한이 해제됐어요',
    accountChangedNotice: '공동 기록 계정 상태가 변경됐어요',
    accountDeletedNotice: '계정과 연결된 데이터를 삭제했어요',
    bootstrapFailed: '공동 기록을 시작하지 못했어요',
    overviewRefreshFailed: '공동 기록을 새로 불러오지 못했어요',
    connectionStatusFailed: '공동 기록 연결 상태를 확인하지 못했어요',
    cacheRehydrated: '저장된 공동 돌봄 정보를 새로 불러왔어요',
    clearRevokedFailed: '해제된 공동 돌봄 정보를 기기에서 지우지 못했어요',
    syncRetryFailed: '동기화를 다시 시도하지 못했어요',
    deleteEventFailedTitle: '삭제할 수 없어요',
    deleteEventFailedMessage:
      '기록을 삭제하지 못했어요. 연결을 확인하고 다시 시도해 주세요.',
    stopSleepFailedTitle: '수면을 종료할 수 없어요',
    stopSleepFailedMessage:
      '수면을 종료하지 못했어요. 연결을 확인하고 다시 시도해 주세요.',
  },

  sync: {
    accessRevoked: '공동 기록 접근 권한을 확인해 주세요',
    conflicts: (count: number) =>
      `동기화 충돌 ${count}건 · 서버 기록을 우선 표시해요`,
    failed: (count: number) => `동기화 실패 ${count}건`,
    pending: (count: number) => `동기화 대기 ${count}건`,
    retryLabel: '동기화 다시 시도',
    reapplyLabel: '내 수정 다시 반영',
    reapplyAction: '다시 반영',
    discardLabel: '서버 기록 그대로 두기',
    discardAction: '그대로 두기',
  },

  home: {
    ageLabel: (days: number) => `생후 ${days}일`,
    lastFeeding: '마지막 수유',
    lastDiaper: '마지막 기저귀',
    lastSleep: '마지막 수면',
    lastTemperature: '마지막 체온',
    lastMedication: '마지막 복약',
    noRecordYet: '아직 기록이 없어요',
    sleeping: '자는 중',
    sharedMode: '공동 기록',
    localMode: '로컬 저장',
    recentSection: '최근 돌봄',
    todaySummary: '오늘 요약',
    sinceMidnight: '자정부터 지금까지',
    feeding: '수유',
    diaper: '기저귀',
    sleep: '수면',
    temperature: '체온',
    medication: '복약',
    quickRecordSection: '빠른 기록',
    quickHint: '바로 남기기',
    firstEntryEyebrow: '첫 기록 가이드',
    firstEntryTitle: '가장 최근의 돌봄부터 남겨보세요',
    firstEntryDescription:
      '수유·기저귀·수면 중 하나를 기록하면, 모든 양육자가 마지막 시각과 오늘 요약을 같이 볼 수 있어요.',
    firstFeedingAction: '첫 수유 기록하기',
    firstDiaperAction: '첫 기저귀 기록하기',
    firstSleepAction: '첫 수면 기록하기',
    wakeUp: '기상',
    endingSleep: '종료 중…',
    pleaseWait: '잠시만 기다려주세요',
    endNow: '지금 종료',
    openSettings: '설정 열기',
    stopSleepLabel: '수면 종료',
    stoppingSleepLabel: '수면 종료 중',
  },

  timeline: {
    title: '타임라인',
    subtitle: '누가 무엇을 기록했는지 시간순으로 확인해요',
    today: '오늘',
    yesterday: '어제',
    liveShared: '● 공동 기록',
    liveLocal: '● 로컬 저장',
    emptyTitle: '첫 돌봄 기록을 남겨보세요',
    emptyText:
      '홈의 큰 버튼으로 수유·기저귀·수면·체온·복약을 빠르게 기록할 수 있어요.',
    deleteHint: '기록을 누르면 수정하고, 길게 누르면 삭제할 수 있어요.',
    deleteConfirmTitle: '기록을 삭제할까요?',
    deleteActionLabel: '기록 삭제',
    deleteAccessibilityHint: '활성화하면 기록 삭제 확인창이 열립니다',
    editActionLabel: '기록 수정',
    editAccessibilityHint: '활성화하면 기록 수정 화면이 열립니다',
    loadingMore: '이전 기록을 불러오는 중…',
    loadMoreError: '이전 기록을 불러오지 못했어요.',
    retryLoadMoreLabel: '이전 기록 다시 불러오기',
    cappedEnd: '기기에 보관할 이전 기록 범위까지 확인했어요',
    allLoaded: '모든 기록을 확인했어요',
  },

  stats: {
    title: '통계',
    subtitle: '돌봄 패턴을 참고용으로 확인해요',
    period12h: '12시간',
    period7d: '7일',
    period30d: '30일',
    feedingCount: '수유 횟수',
    totalSleep: '총 수면',
    diaperTotal: (count: number) => `${count}회 기저귀`,
    perBucketCount: '구간별 기록',
    sleepDuration: '수면 시간',
    perBucketDuration: '구간별 시간',
    detailChecking: '상세 통계 이용 상태를 확인하고 있어요',
    detailLockedTitle: '상세 통계 24시간 열기',
    detailLockedDescription:
      '선택형 광고 한 편을 보면 구간별 수유·수면 차트를 24시간 확인할 수 있어요.',
    unlockAction: '광고 보고 상세 통계 열기',
    adLoading: '광고 준비 중…',
    adUnavailable: '광고를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
    disclaimer:
      '통계는 돌봄 기록을 요약한 참고 정보이며 의료 판단이나 진단을 제공하지 않습니다.',
  },

  more: {
    title: '더보기',
    subtitle: '그룹과 앱 설정을 관리해요',
    groupEyebrow: '돌봄 그룹',
    groupName: (babyName: string) => `${babyName}이네`,
    sharedModeBadge: '공동 기록 모드',
    localModeBadge: '로컬 개발 모드',
    mePrefix: '나 · ',
    roleOwner: '소유자',
    roleMember: '구성원',
    inviteLabel: '양육자 초대 코드',
    invitePreviewLabel: '초대 코드 미리보기',
    inviteExpired: '초대 코드가 만료됐어요',
    inviteValidUntil: (formattedDate: string) => `${formattedDate}까지 유효`,
    inviteCreatingLabel: '초대 코드 만드는 중',
    inviteShareLabel: '초대 코드 공유',
    inviteRecreateLabel: '새 초대 코드 만들기',
    inviteCreateLabel: '초대 코드 만들기',
    inviteCreating: '만드는 중…',
    inviteRecreate: '새 코드 만들기',
    inviteCreate: '코드 만들기',
    inviteOwnerOnly: '소유자만 초대할 수 있어요',
    inviteLocalDisabled: '연결 후 활성화',
    shareMessage: (code: string) =>
      [
        '함께봄 돌봄 그룹에 초대했어요.',
        `초대 코드: ${code}`,
        '',
        '앱을 설치한 뒤 "초대 코드가 있어요"에서 이 코드를 입력하면 함께 기록할 수 있어요.',
        `Android: ${androidStoreUrl}`,
        `iPhone: ${appleStoreUrl}`,
      ].join('\n'),
    settingsSection: '설정',
    babyProfileEditTitle: '아기 정보 수정',
    babyProfileEditDetail: '이름과 생년월일을 고쳐요',
    babyProfileNameLabel: '아기 이름',
    babyProfileBirthDateLabel: '생년월일',
    babyProfileBirthDatePlaceholder: 'YYYY-MM-DD',
    babyProfileSave: '저장',
    babyProfileSaving: '저장 중…',
    babyProfileFailedTitle: '아기 정보를 저장하지 못했어요',
    babyProfileNameInvalid: '아기 이름을 1~80자로 입력해 주세요.',
    babyProfileBirthDateInvalid: '생년월일을 YYYY-MM-DD의 실제 날짜로 입력해 주세요.',
    babyProfileBirthDateFuture: '생년월일은 오늘이나 그 이전 날짜여야 해요.',
    babyProfileNotOwner: '돌봄 그룹 소유자만 아기 정보를 수정할 수 있어요.',
    babyProfileSaveFailed: '기존 정보는 유지했어요. 연결을 확인하고 다시 시도해 주세요.',
    unitTitle: '단위',
    unitDetail: 'ml',
    appearanceTitle: '화면 모드',
    appearanceDetail: '시스템 설정 사용',
    syncRefreshTitle: '구성원 목록 새로고침',
    syncRefreshDetail: '최신 구성원 목록을 다시 확인해요',
    syncStatusTitle: '동기화 상태',
    syncStatusShared: '공동 기록 자동 동기화',
    syncStatusLocal: '기기 로컬 저장 · 개발 모드',
    languageTitle: '언어',
    privacySection: '데이터와 개인정보',
    privacyPolicyTitle: '개인정보 처리방침',
    privacyPolicyDetail: '성인 양육자용 · 비의료 목적',
    adPrivacyTitle: '광고 개인정보 선택',
    adPrivacyDetail: '동의·거부 선택을 다시 확인하거나 변경해요',
    adPrivacyNotRequiredTitle: '현재 지역에는 별도 선택이 필요하지 않아요',
    adPrivacyNotRequiredMessage:
      '적용되는 개인정보 선택 항목이 생기면 이 메뉴에서 변경할 수 있어요.',
    adPrivacyFailedTitle: '광고 개인정보 선택을 열지 못했어요',
    adPrivacyFailedMessage: '인터넷 연결을 확인하고 다시 시도해 주세요.',
    deleteAccountTitle: '계정 삭제',
    deleteAccountPending: '계정 삭제 중…',
    deleteAccountOwnerDetail: '계정과 돌봄 그룹의 모든 데이터를 영구 삭제해요',
    deleteAccountMemberDetail: '계정과 내 멤버십·작성 기록을 영구 삭제해요',
    deleteAccountConfirmTitle: '계정을 영구 삭제할까요?',
    deleteAccountOwnerConsequence:
      '계정과 이 돌봄 그룹의 아기 정보·모든 돌봄 기록이 영구 삭제됩니다. 다른 구성원도 이 그룹에 더 이상 접근할 수 없습니다.',
    deleteAccountMemberConsequence:
      '계정과 그룹 멤버십, 내가 남긴 돌봄 기록이 영구 삭제됩니다. 다른 구성원의 그룹과 기록은 유지됩니다.',
    deleteAccountIrreversible: '삭제한 데이터는 복구할 수 없습니다.',
    deleteAccountConfirmAction: '계정 삭제',
    resetTitle: '로컬 데이터 초기화',
    resetConfirmTitle: '로컬 데이터를 초기화할까요?',
    resetConfirmMessage:
      '이 기기에 저장한 모든 돌봄 기록과 프로필이 삭제됩니다.',
    resetFailedTitle: '초기화하지 못했어요',
    resetFailedMessage: '기기 데이터를 지우지 못했습니다. 다시 시도해 주세요.',
    inviteFailedTitle: '초대 코드를 만들지 못했어요',
    inviteFailedMessage: '연결을 확인하고 잠시 후 다시 시도해 주세요.',
    shareFailedTitle: '초대 코드를 공유하지 못했어요',
    shareFailedMessage: '기기의 공유 기능을 열지 못했어요. 다시 시도해 주세요.',
    refreshMembersFailedTitle: '구성원 목록을 새로고침하지 못했어요',
    refreshMembersFailedMessage: '연결을 확인하고 다시 시도해 주세요.',
    removeMemberLabel: (name: string) => `${name} 내보내기`,
    removeMemberConfirmTitle: (name: string) => `${name}님을 그룹에서 내보낼까요?`,
    removeMemberConfirmMessage:
      '내보낸 구성원은 이 그룹의 아기 정보와 돌봄 기록에 더 이상 접근할 수 없습니다. 이 동작은 되돌릴 수 없고, 다시 함께하려면 새 초대 코드가 필요합니다.',
    removeMemberConfirmAction: '내보내기',
    removeMemberFailedTitle: '구성원을 내보내지 못했어요',
    removeMemberFailedMessage: '연결을 확인하고 다시 시도해 주세요.',
    privacyOpenFailedTitle: '개인정보 처리방침을 열지 못했어요',
    privacyOpenFailedMessage: '인터넷 연결을 확인하고 다시 시도해 주세요.',
    deleteAccountFailedTitle: '계정을 삭제하지 못했어요',
    deleteAccountFailedMessage: '연결을 확인하고 잠시 후 다시 시도해 주세요.',
  },

  quickRecord: {
    feedingTitle: '수유 기록',
    diaperTitle: '기저귀 기록',
    sleepTitle: '수면 시작',
    temperatureTitle: '체온 기록',
    medicationTitle: '복약 기록',
    editTitle: '돌봄 기록 수정',
    typeLabel: '유형',
    feedingBreast: '모유',
    feedingPumped: '유축',
    feedingFormula: '분유',
    feedingSolid: '이유식',
    leftWithDuration: (duration: string) => `왼쪽 ${duration}`,
    rightWithDuration: (duration: string) => `오른쪽 ${duration}`,
    timerPause: '일시정지',
    timerResume: '계속',
    timerStart: '시작',
    timerActionLabel: (side: 'left' | 'right', action: string) =>
      `${side === 'left' ? '왼쪽' : '오른쪽'} 모유 타이머 ${action}`,
    timerResetLabel: '모유 타이머 초기화',
    amountLabel: '양',
    decreaseVolumeLabel: '수유량 10밀리리터 줄이기',
    increaseVolumeLabel: '수유량 10밀리리터 늘리기',
    volumeValueLabel: (milliliters: number) => `수유량 ${milliliters}밀리리터`,
    diaperLabel: '상태',
    diaperWet: '소변',
    diaperDirty: '대변',
    diaperMixed: '둘 다',
    sleepTypeLabel: '수면 유형',
    sleepNap: '낮잠',
    sleepNight: '밤잠',
    sleepNotice:
      '선택한 기록 시각부터 수면 시간을 측정해요. 홈의 ‘기상’ 버튼으로 종료합니다.',
    temperatureLabel: '체온',
    decreaseTemperatureLabel: '체온 0.1도 낮추기',
    increaseTemperatureLabel: '체온 0.1도 높이기',
    temperatureValueLabel: (temperature: number) =>
      `체온 ${temperature.toFixed(1)}도`,
    measurementSiteLabel: '측정 부위',
    siteArmpit: '겨드랑이',
    siteEar: '귀',
    siteForehead: '이마',
    siteOral: '입',
    siteRectal: '직장',
    siteOther: '기타',
    medicationPresetLabel: '약 선택',
    medicationAcetaminophen: '아세트아미노펜',
    medicationIbuprofen: '이부프로펜',
    medicationAntibiotic: '항생제',
    medicationCustom: '직접 입력',
    medicationRecent: '최근 직접 입력한 약',
    medicationNameLabel: '약 이름',
    medicationNamePlaceholder: '제품명 또는 처방 약 이름',
    doseLabel: '실제로 먹인 양',
    doseAmountPlaceholder: '예: 3.5',
    doseUnitLabel: '단위',
    intervalLabel: '최소 복용 간격',
    intervalHint: '제품 라벨이나 의료진 안내에서 확인한 간격을 입력하세요.',
    intervalHours: (hours: number) => `${hours}시간`,
    antipyreticScheduleTitle: '해열제 간격 확인',
    noPriorDose: '이전 기록 없음',
    nextDoseAt: (formattedTime: string) => `다음 기록 가능 ${formattedTime}`,
    doseReady: '확인한 간격이 지났어요',
    medicationSafetyNotice:
      '함께봄은 의료기기가 아니며 용량을 추천하지 않습니다. 제품 라벨 또는 의료진 안내를 따르세요. 특히 2세 미만 아세트아미노펜과 6개월 미만 이부프로펜은 의료진 안내를 먼저 확인하고, 두 해열제를 동시에 먹이거나 임의로 교차 복용하지 마세요.',
    medicationTooSoonWarning: (name: string) =>
      `${name}의 확인한 최소 간격 안에 있는 기록입니다. 실제 복약 시각이 맞는지 다시 확인해 주세요.`,
    simultaneousAntipyreticWarning:
      '다른 해열제와 같은 시각으로 기록되어 있습니다. 의료진 안내와 실제 복약 시각을 다시 확인해 주세요.',
    medicationHistoryIncompleteWarning:
      '전체 복약 기록을 확인하지 못했습니다. 다른 기기의 기록과 실제 복약 시각을 확인한 뒤 저장해 주세요.',
    acknowledgeAndSave: '경고 확인 후 기록',
    medicationNameRequired: '약 이름을 입력해 주세요.',
    medicationDoseRequired: '실제로 먹인 양을 입력해 주세요.',
    occurredAtLabel: '기록 시각',
    occurredAtHint: '선택한 시각으로 저장',
    shiftBackLabel: '기록 시각 10분 앞당기기',
    shiftBack: '−10분',
    setNowLabel: '기록 시각을 지금으로 설정',
    noteLabel: '메모 (선택)',
    notePlaceholder: '특이사항을 남겨주세요',
    saveLabel: '돌봄 기록 저장',
    savingLabel: '돌봄 기록 저장 중',
    saving: '저장 중…',
    save: '저장하기',
    saveGuidance: '모유 타이머를 1초 이상 측정하면 저장할 수 있어요.',
    saveFailed: '기록을 저장하지 못했어요. 연결을 확인하고 다시 시도해 주세요.',
  },

  onboarding: {
    eyebrow: '함께봄 공동 기록',
    chooseTitle: '내가 없을 때의 돌봄도 한눈에',
    chooseSubtitle:
      '수유·기저귀·수면·체온·복약을 빠르게 남기고, 교대하는 양육자와 바로 공유하세요.',
    quickBenefitTitle: '10초 기록',
    handoffBenefitTitle: '쉬운 인수인계',
    privateBenefitTitle: '초대 전용 공유',
    createChoiceTitle: '내 아기로 시작',
    createChoiceDescription: '비공개 돌봄 그룹을 만들고 첫 기록을 남겨요',
    joinChoiceTitle: '초대 코드가 있어요',
    joinChoiceDescription: '기존 그룹에 참여해 공동 기록을 확인해요',
    caregiverTitle: '어떻게 불러드릴까요?',
    caregiverSubtitle: '함께 기록할 때 표시되는 이름이에요.',
    caregiverLabel: '양육자 이름',
    caregiverPlaceholder: '예: 엄마, 아빠, 할머니',
    babyNameTitle: '아기 이름을 알려주세요',
    babyNameSubtitle: '돌봄 그룹에서 사용할 아기 이름이에요.',
    babyNameLabel: '아기 이름',
    babyNamePlaceholder: '예: 지안',
    birthDateTitle: '아기는 언제 태어났나요?',
    birthDateSubtitle: '홈에서 아기의 생후 일수를 표시하는 데 사용해요.',
    birthDateLabel: '아기 생년월일',
    birthDatePlaceholder: '날짜 선택',
    birthDatePick: '선택',
    birthDateSelectAccessibilityLabel: '아기 생년월일 선택',
    birthDateCalendarAccessibilityLabel: '아기 생년월일 달력',
    birthDatePreviousYearLabel: '이전 해',
    birthDatePreviousMonthLabel: '이전 달',
    birthDateNextMonthLabel: '다음 달',
    birthDateNextYearLabel: '다음 해',
    inviteCodeTitle: '초대 코드를 입력해 주세요',
    inviteCodeSubtitle: '그룹 소유자에게 받은 6자리 코드예요.',
    inviteCodeLabel: '초대 코드',
    inviteCodeNotFound: '붙여넣은 내용에서 6자리 코드를 찾지 못했어요. 코드를 확인해 주세요.',
    preparing: '공동 기록을 준비하는 중…',
    createAction: '돌봄 그룹 만들기',
    joinAction: '돌봄 그룹 참여하기',
    createFailed:
      '돌봄 그룹을 만들지 못했어요. 연결을 확인하고 다시 시도해 주세요.',
    joinFailed:
      '돌봄 그룹에 참여하지 못했어요. 코드를 확인하거나 새 코드를 요청해 주세요.',
    notice:
      '앱을 삭제하거나 기기를 바꾸면 현재 계정과 기록에 다시 접근하지 못할 수 있어요.',
  },

  updateGate: {
    update: '업데이트하기',
    later: '나중에',
  },
};

export type Strings = typeof ko;

const en: Strings = {
  intlLocale: 'en-US',
  languageName: 'English',

  common: {
    retry: 'Try again',
    refresh: 'Refresh',
    cancel: 'Cancel',
    delete: 'Delete',
    close: 'Close',
    next: 'Next',
    back: 'Back',
    share: 'Share',
    now: 'Now',
    reset: 'Reset',
    otherCaregiver: 'Another caregiver',
  },

  tabs: {
    home: 'Home',
    timeline: 'Timeline',
    stats: 'Stats',
    more: 'More',
  },

  duration: {
    hoursMinutes: (hours: number, minutes: number) => `${hours}h ${minutes}m`,
    minutes: (minutes: number) => `${minutes}m`,
    seconds: (seconds: number) => `${seconds}s`,
  },

  timeAgo: {
    justNow: 'Just now',
    soon: 'Soon',
    past: (value: number, unit: TimeAgoUnit) =>
      `${value} ${englishPlural(value, unit)} ago`,
    future: (value: number, unit: TimeAgoUnit) =>
      `in ${value} ${englishPlural(value, unit)}`,
  },

  event: {
    breastMilk: (sides: string) => `Breastfeeding · ${sides}`,
    leftSide: (duration: string) => `Left ${duration}`,
    rightSide: (duration: string) => `Right ${duration}`,
    formula: 'Formula',
    pumped: 'Pumped milk',
    solid: 'Solids',
    volume: (label: string, milliliters: number) => `${label} ${milliliters}ml`,
    diaperWet: 'Pee',
    diaperDirty: 'Poop',
    diaperMixed: 'Pee + poop',
    diaper: (label: string) => `Diaper · ${label}`,
    nap: 'Nap',
    nightSleep: 'Night sleep',
    sleepEnded: (label: string, duration: string) => `${label} · ${duration}`,
    sleepActive: (label: string) => `${label} in progress`,
    temperature: (temperature: number, site: string) =>
      `Temperature · ${temperature.toFixed(1)}°C · ${site}`,
    temperatureArmpit: 'Armpit',
    temperatureEar: 'Ear',
    temperatureForehead: 'Forehead',
    temperatureOral: 'Mouth',
    temperatureRectal: 'Rectal',
    temperatureOther: 'Other',
    medication: (name: string, dose: string) => `Medication · ${name} ${dose}`,
  },

  app: {
    loadingTitle: 'Getting your shared log ready',
    loadingText: 'Checking your account and care group',
    errorTitle: "Can't connect to your shared log",
    splashTitle: 'Care for today, together',
    splashText: 'Getting your care log ready',
    runtimeLoadErrorTitle: "Can't open your shared log",
    runtimeLoadErrorMessage:
      "Couldn't load the shared log screen. Please try again.",
    runtimeLoadRetryLabel: 'Reopen the shared log screen',
    eventSaved: 'Care log saved',
    eventUpdated: 'Care log updated',
    eventDeleted: 'Entry deleted',
    sleepRecorded: 'Sleep duration saved',
    membershipRemovedNotice: 'Your access to this care group was removed',
    accountChangedNotice: 'Your shared log account status changed',
    accountDeletedNotice: 'Your account and its data were deleted',
    bootstrapFailed: "Couldn't start your shared log",
    overviewRefreshFailed: "Couldn't refresh your shared log",
    connectionStatusFailed: "Couldn't check the shared log connection",
    cacheRehydrated: 'Reloaded your saved care group data',
    clearRevokedFailed: "Couldn't clear the revoked care group data from this device",
    syncRetryFailed: "Couldn't retry syncing",
    deleteEventFailedTitle: "Can't delete",
    deleteEventFailedMessage:
      "Couldn't delete this entry. Check your connection and try again.",
    stopSleepFailedTitle: "Can't end sleep",
    stopSleepFailedMessage:
      "Couldn't end this sleep session. Check your connection and try again.",
  },

  sync: {
    accessRevoked: 'Please check your access to this shared log',
    conflicts: (count: number) =>
      `${count} sync ${englishPlural(count, 'conflict')} · showing the server entry`,
    failed: (count: number) => `${count} sync ${englishPlural(count, 'failure')}`,
    pending: (count: number) =>
      `${count} ${count === 1 ? 'entry' : 'entries'} waiting to sync`,
    retryLabel: 'Retry syncing',
    reapplyLabel: 'Reapply my changes',
    reapplyAction: 'Reapply',
    discardLabel: 'Keep the server entry',
    discardAction: 'Keep server',
  },

  home: {
    ageLabel: (days: number) => `${days} ${englishPlural(days, 'day')} old`,
    lastFeeding: 'Last feeding',
    lastDiaper: 'Last diaper',
    lastSleep: 'Last sleep',
    lastTemperature: 'Last temperature',
    lastMedication: 'Last medication',
    noRecordYet: 'No entries yet',
    sleeping: 'Sleeping',
    sharedMode: 'Shared',
    localMode: 'On device',
    recentSection: 'Recent care',
    todaySummary: "Today's summary",
    sinceMidnight: 'Since midnight',
    feeding: 'Feeding',
    diaper: 'Diaper',
    sleep: 'Sleep',
    temperature: 'Temperature',
    medication: 'Medication',
    quickRecordSection: 'Quick log',
    quickHint: 'Log it now',
    firstEntryEyebrow: 'QUICK START',
    firstEntryTitle: 'What happened most recently?',
    firstEntryDescription:
      "Log one update now. Every caregiver in your group will see the latest time and today's summary.",
    firstFeedingAction: 'Log the first feeding',
    firstDiaperAction: 'Log the first diaper',
    firstSleepAction: 'Log the first sleep',
    wakeUp: 'Wake up',
    endingSleep: 'Ending…',
    pleaseWait: 'One moment',
    endNow: 'End now',
    openSettings: 'Open settings',
    stopSleepLabel: 'End sleep',
    stoppingSleepLabel: 'Ending sleep',
  },

  timeline: {
    title: 'Timeline',
    subtitle: 'See who logged what, in order',
    today: 'Today',
    yesterday: 'Yesterday',
    liveShared: '● Shared',
    liveLocal: '● On device',
    emptyTitle: 'Add your first care entry',
    emptyText:
      'Use the big buttons on Home to log feeding, diapers, sleep, temperature, and medication.',
    deleteHint: 'Tap an entry to edit it, or press and hold to delete it.',
    deleteConfirmTitle: 'Delete this entry?',
    deleteActionLabel: 'Delete entry',
    deleteAccessibilityHint: 'Activating opens a delete confirmation',
    editActionLabel: 'Edit entry',
    editAccessibilityHint: 'Activating opens the entry editor',
    loadingMore: 'Loading earlier entries…',
    loadMoreError: "Couldn't load earlier entries.",
    retryLoadMoreLabel: 'Reload earlier entries',
    cappedEnd: "You've reached the earliest entries kept on this device",
    allLoaded: "You've reached the end",
  },

  stats: {
    title: 'Stats',
    subtitle: 'Review care patterns for reference',
    period12h: '12 hours',
    period7d: '7 days',
    period30d: '30 days',
    feedingCount: 'Feedings',
    totalSleep: 'Total sleep',
    diaperTotal: (count: number) => `${count} ${englishPlural(count, 'diaper')}`,
    perBucketCount: 'Per interval',
    sleepDuration: 'Sleep duration',
    perBucketDuration: 'Per interval',
    detailChecking: 'Checking detailed stats access…',
    detailLockedTitle: 'Unlock detailed stats for 24 hours',
    detailLockedDescription:
      'Watch one optional ad to view interval feeding and sleep charts for 24 hours.',
    unlockAction: 'Watch ad and unlock',
    adLoading: 'Preparing ad…',
    adUnavailable: 'The ad is unavailable. Please try again later.',
    disclaimer:
      'Stats summarize your care log for reference only and do not provide medical judgment or diagnosis.',
  },

  more: {
    title: 'More',
    subtitle: 'Manage your group and app settings',
    groupEyebrow: 'Care group',
    groupName: (babyName: string) => `${babyName}'s group`,
    sharedModeBadge: 'Shared logging',
    localModeBadge: 'Local dev mode',
    mePrefix: 'You · ',
    roleOwner: 'Owner',
    roleMember: 'Member',
    inviteLabel: 'Caregiver invite code',
    invitePreviewLabel: 'Invite code preview',
    inviteExpired: 'This invite code expired',
    inviteValidUntil: (formattedDate: string) => `Valid until ${formattedDate}`,
    inviteCreatingLabel: 'Creating invite code',
    inviteShareLabel: 'Share invite code',
    inviteRecreateLabel: 'Create a new invite code',
    inviteCreateLabel: 'Create invite code',
    inviteCreating: 'Creating…',
    inviteRecreate: 'New code',
    inviteCreate: 'Create code',
    inviteOwnerOnly: 'Only the owner can invite',
    inviteLocalDisabled: 'Available once connected',
    shareMessage: (code: string) =>
      [
        "You're invited to a BabyNest care group.",
        `Invite code: ${code}`,
        '',
        'Install the app, tap "I have an invite code", and enter this code to log care together.',
        `Android: ${androidStoreUrl}`,
        `iPhone: ${appleStoreUrl}`,
      ].join('\n'),
    settingsSection: 'Settings',
    babyProfileEditTitle: 'Edit baby profile',
    babyProfileEditDetail: 'Correct the name and date of birth',
    babyProfileNameLabel: 'Baby name',
    babyProfileBirthDateLabel: 'Date of birth',
    babyProfileBirthDatePlaceholder: 'YYYY-MM-DD',
    babyProfileSave: 'Save',
    babyProfileSaving: 'Saving…',
    babyProfileFailedTitle: "Couldn't save the baby profile",
    babyProfileNameInvalid: 'Enter a baby name between 1 and 80 characters.',
    babyProfileBirthDateInvalid: 'Enter a real date in YYYY-MM-DD format.',
    babyProfileBirthDateFuture: 'The date of birth must be today or earlier.',
    babyProfileNotOwner: 'Only the care group owner can edit the baby profile.',
    babyProfileSaveFailed: 'The existing profile is unchanged. Check your connection and try again.',
    unitTitle: 'Unit',
    unitDetail: 'ml',
    appearanceTitle: 'Appearance',
    appearanceDetail: 'Follow system setting',
    syncRefreshTitle: 'Refresh member list',
    syncRefreshDetail: 'Check for the latest members',
    syncStatusTitle: 'Sync status',
    syncStatusShared: 'Shared log syncs automatically',
    syncStatusLocal: 'Stored on this device · dev mode',
    languageTitle: 'Language',
    privacySection: 'Data and privacy',
    privacyPolicyTitle: 'Privacy policy',
    privacyPolicyDetail: 'For adult caregivers · non-medical',
    adPrivacyTitle: 'Ad privacy choices',
    adPrivacyDetail: 'Review or change your consent and opt-out choices',
    adPrivacyNotRequiredTitle: 'No separate choice is required in your region',
    adPrivacyNotRequiredMessage:
      'If privacy choices become applicable, you can change them here.',
    adPrivacyFailedTitle: "Couldn't open ad privacy choices",
    adPrivacyFailedMessage: 'Check your internet connection and try again.',
    deleteAccountTitle: 'Delete account',
    deleteAccountPending: 'Deleting account…',
    deleteAccountOwnerDetail:
      'Permanently delete your account and all data in this care group',
    deleteAccountMemberDetail:
      'Permanently delete your account, membership, and your own entries',
    deleteAccountConfirmTitle: 'Permanently delete your account?',
    deleteAccountOwnerConsequence:
      "Your account, this care group's baby profile, and every care entry will be permanently deleted. Other members will lose access to this group.",
    deleteAccountMemberConsequence:
      'Your account, your membership, and the entries you created will be permanently deleted. Other members keep their group and entries.',
    deleteAccountIrreversible: 'Deleted data cannot be recovered.',
    deleteAccountConfirmAction: 'Delete account',
    resetTitle: 'Reset local data',
    resetConfirmTitle: 'Reset local data?',
    resetConfirmMessage:
      'Every care entry and profile stored on this device will be deleted.',
    resetFailedTitle: "Couldn't reset",
    resetFailedMessage: "Couldn't clear this device's data. Please try again.",
    inviteFailedTitle: "Couldn't create an invite code",
    inviteFailedMessage: 'Check your connection and try again in a moment.',
    shareFailedTitle: "Couldn't share the invite code",
    shareFailedMessage: "Couldn't open your device's share sheet. Please try again.",
    refreshMembersFailedTitle: "Couldn't refresh the member list",
    refreshMembersFailedMessage: 'Check your connection and try again.',
    removeMemberLabel: (name: string) => `Remove ${name}`,
    removeMemberConfirmTitle: (name: string) => `Remove ${name} from the group?`,
    removeMemberConfirmMessage:
      "Removed members can no longer access this group's baby info and care records. This cannot be undone, and rejoining requires a new invite code.",
    removeMemberConfirmAction: 'Remove',
    removeMemberFailedTitle: "Couldn't remove the member",
    removeMemberFailedMessage: 'Check your connection and try again.',
    privacyOpenFailedTitle: "Couldn't open the privacy policy",
    privacyOpenFailedMessage: 'Check your internet connection and try again.',
    deleteAccountFailedTitle: "Couldn't delete your account",
    deleteAccountFailedMessage: 'Check your connection and try again in a moment.',
  },

  quickRecord: {
    feedingTitle: 'Log feeding',
    diaperTitle: 'Log diaper',
    sleepTitle: 'Start sleep',
    temperatureTitle: 'Log temperature',
    medicationTitle: 'Log medication',
    editTitle: 'Edit care entry',
    typeLabel: 'Type',
    feedingBreast: 'Breast',
    feedingPumped: 'Pumped',
    feedingFormula: 'Formula',
    feedingSolid: 'Solids',
    leftWithDuration: (duration: string) => `Left ${duration}`,
    rightWithDuration: (duration: string) => `Right ${duration}`,
    timerPause: 'Pause',
    timerResume: 'Resume',
    timerStart: 'Start',
    timerActionLabel: (side: 'left' | 'right', action: string) =>
      `${side === 'left' ? 'Left' : 'Right'} breastfeeding timer ${action}`,
    timerResetLabel: 'Reset breastfeeding timer',
    amountLabel: 'Amount',
    decreaseVolumeLabel: 'Decrease amount by 10 milliliters',
    increaseVolumeLabel: 'Increase amount by 10 milliliters',
    volumeValueLabel: (milliliters: number) => `${milliliters} milliliters`,
    diaperLabel: 'Contents',
    diaperWet: 'Pee',
    diaperDirty: 'Poop',
    diaperMixed: 'Both',
    sleepTypeLabel: 'Sleep type',
    sleepNap: 'Nap',
    sleepNight: 'Night',
    sleepNotice:
      'Sleep is timed from the entry time you pick. End it with the "Wake up" button on Home.',
    temperatureLabel: 'Temperature',
    decreaseTemperatureLabel: 'Decrease temperature by 0.1 degree',
    increaseTemperatureLabel: 'Increase temperature by 0.1 degree',
    temperatureValueLabel: (temperature: number) =>
      `${temperature.toFixed(1)} degrees Celsius`,
    measurementSiteLabel: 'Measurement site',
    siteArmpit: 'Armpit',
    siteEar: 'Ear',
    siteForehead: 'Forehead',
    siteOral: 'Mouth',
    siteRectal: 'Rectal',
    siteOther: 'Other',
    medicationPresetLabel: 'Medication',
    medicationAcetaminophen: 'Acetaminophen',
    medicationIbuprofen: 'Ibuprofen',
    medicationAntibiotic: 'Antibiotic',
    medicationCustom: 'Custom',
    medicationRecent: 'Recently entered medications',
    medicationNameLabel: 'Medication name',
    medicationNamePlaceholder: 'Product or prescription name',
    doseLabel: 'Amount actually given',
    doseAmountPlaceholder: 'e.g. 3.5',
    doseUnitLabel: 'Unit',
    intervalLabel: 'Minimum dose interval',
    intervalHint: 'Enter the interval from the product label or your clinician.',
    intervalHours: (hours: number) => `${hours}h`,
    antipyreticScheduleTitle: 'Fever medicine intervals',
    noPriorDose: 'No previous entry',
    nextDoseAt: (formattedTime: string) => `Next entry at ${formattedTime}`,
    doseReady: 'The interval you entered has passed',
    medicationSafetyNotice:
      'BabyNest is not a medical device and does not recommend doses. Follow the product label or your clinician. Confirm clinical guidance before acetaminophen under age 2 or ibuprofen under 6 months. Do not give both fever medicines at the same time or alternate them without clinical advice.',
    medicationTooSoonWarning: (name: string) =>
      `This entry falls inside the interval you entered for ${name}. Check the actual time again.`,
    simultaneousAntipyreticWarning:
      'Another fever medicine is logged at the same time. Check the clinical instructions and actual time again.',
    medicationHistoryIncompleteWarning:
      'The full medication history is unavailable. Check other devices and the actual dose time before saving.',
    acknowledgeAndSave: 'Confirm warning and log',
    medicationNameRequired: 'Enter the medication name.',
    medicationDoseRequired: 'Enter the amount actually given.',
    occurredAtLabel: 'Entry time',
    occurredAtHint: 'Saved with the time you pick',
    shiftBackLabel: 'Move entry time 10 minutes earlier',
    shiftBack: '−10 min',
    setNowLabel: 'Set entry time to now',
    noteLabel: 'Note (optional)',
    notePlaceholder: 'Add anything worth remembering',
    saveLabel: 'Save care entry',
    savingLabel: 'Saving care entry',
    saving: 'Saving…',
    save: 'Save',
    saveGuidance: 'Run the breastfeeding timer for at least a second to save.',
    saveFailed:
      "Couldn't save this entry. Check your connection and try again.",
  },

  onboarding: {
    eyebrow: 'BABYNEST SHARED LOG',
    chooseTitle: "Know what happened, even when you weren't there",
    chooseSubtitle:
      'Log feedings, diapers, sleep, temperature, and medication in seconds, then keep every caregiver in sync.',
    quickBenefitTitle: 'Log care in seconds',
    handoffBenefitTitle: 'Easy handoffs',
    privateBenefitTitle: 'Invite-only sharing',
    createChoiceTitle: 'Set up my baby',
    createChoiceDescription: 'Create a private care group and add the first update',
    joinChoiceTitle: 'I have an invite code',
    joinChoiceDescription: 'Join an existing group and see the shared log',
    caregiverTitle: 'What should we call you?',
    caregiverSubtitle: 'This name shows up on the entries you log.',
    caregiverLabel: 'Caregiver name',
    caregiverPlaceholder: 'e.g. Mom, Dad, Grandma',
    babyNameTitle: "What's your baby's name?",
    babyNameSubtitle: "The baby's name used inside your care group.",
    babyNameLabel: 'Baby name',
    babyNamePlaceholder: 'e.g. Jian',
    birthDateTitle: 'When was your baby born?',
    birthDateSubtitle: "Used to show your baby's age in days on Home.",
    birthDateLabel: 'Date of birth',
    birthDatePlaceholder: 'Pick a date',
    birthDatePick: 'Pick',
    birthDateSelectAccessibilityLabel: "Select baby's date of birth",
    birthDateCalendarAccessibilityLabel: "Baby's date of birth calendar",
    birthDatePreviousYearLabel: 'Previous year',
    birthDatePreviousMonthLabel: 'Previous month',
    birthDateNextMonthLabel: 'Next month',
    birthDateNextYearLabel: 'Next year',
    inviteCodeTitle: 'Enter your invite code',
    inviteCodeSubtitle: 'The 6-character code from the group owner.',
    inviteCodeLabel: 'Invite code',
    inviteCodeNotFound: "We couldn't find a 6-character code in what you pasted. Please check the code.",
    preparing: 'Getting your shared log ready…',
    createAction: 'Create care group',
    joinAction: 'Join care group',
    createFailed:
      "Couldn't create the care group. Check your connection and try again.",
    joinFailed:
      "Couldn't join the care group. Check the code or ask for a new one.",
    notice:
      'If you delete the app or switch devices, you may lose access to this account and its entries.',
  },

  updateGate: {
    update: 'Update',
    later: 'Later',
  },
};

const STRINGS: Readonly<Record<AppLocale, Strings>> = {ko, en};

export function createStrings(locale: AppLocale): Strings {
  return STRINGS[locale];
}
