packages:
  - apps/*
  - firebase/functions
  - packages/*

allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  protobufjs: true
  re2: true

minimumReleaseAgeExclude:
  - '@seorilabs/platform-sdk@0.4.0 || 0.5.0'

patchedDependencies:
  '@react-native/gradle-plugin@0.85.3': patches/@react-native__gradle-plugin@0.85.3.patch
